config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'comments/new'
  get 'comments/create'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/create'
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  put '/users/:id', to: 'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'
  
  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  get 'friendships/create'
  get 'users/index'
  get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :content, length: { in: 1..100 }, allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @post = Post.find(params[:comment][:post_id])
    if @comment.save
      @notification = new_notification(@post.user, @post.id, 'comment')
      @notification.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    return unless current_user.id == @current_user.user_id
    
    @comment.destroy
    flash[:success] = 'Comment deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% object.comments.each do |c| %>
  <div class=" p-2">
        <div class="row mt-3">
          <div class="ml-2">
          <% if c.user.image_url %>
            <%= image_tag(c.user.image.url, class: "img-profile") %>
          <% end %>
        </div>
        <div class="mt-2">
            <div class="col font-weight-bold">
              <%= link_to user_path(c.user), class: "font-raleway" do %>
                <%= c.user.full_name %>
              <% end %>
            </div>
            <div class="col size-12">Posted <%= distance_of_time_in_words(c.created_at, Time.now) %> ago</div>
        </div>
    <div>

    <div class= "row ml-5 pl-1">
          <div class="col-auto font-rale text-post">
            <%= c.content %>
            <% if current_user.id == c.user_id %>
              <%= link_to comment_path(c), method: :delete, data: { confirm: "Are you sure?"} do %>
                <i class="fas fa-trash hover-red">
              <% end %>
            <% end %>
          </div>
    </div>
    <div class="row ml-5 pl-1">
      <div class="col-auto"><%= render 'likes/like_comments', object: c %></div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for @comment = Comment.new do |f| %>
  <%= render "devise/shared/error_messages", resource: @comment %>
  <%= f.hidden_field :post_id, :value => object.id %>
  <div class="form-group">
    <%= f.text_area :content, class: "comment-box", placeholder: "Type comment here." %>
  </div>
  <div>
    <%= f.submit 'Comment', class:"btn bg-secondary m-0" %>
  </div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>