config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'comments/new'
  get 'comments/create'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/create'
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  put '/users/:id', to: 'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'
  
  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  get 'friendships/create'
  get 'users/index'
  get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :content, length: { in: 3..800 }, allow_blank: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @our_posts = current_user.friends_and_own_posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    return unless current_user.id == @post.user_id
    
    @post.destroy
    flash[:success] = 'Post deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def posts_params
    params.require(:post).permit(:content, :imageURL)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_layout.html.erb
<div class="col-md-7 mx-auto card-lg bg-light shadow">

  <div class="container">
    <div class="row mt-3">
      <div class="m1-2">
      <% if object.user.image, class: "img-profile" %>
        <%= image_tag(object.user.image.url, class: "img-profile") %>
      <% end %>
      </div>
      <div class="mt-2">
        <div class="col font-weight-bold">
          <%= link_to user_path(object.user), class: "font-raleway" do %>
            <%= object.user.full_name %>
          <% end %>
        </div>
        <div class="col size-12">Posted<%= distance_of_time_in_words(object.created_at, Time.now) %> ago</div>
      </div>
    </div>
  </div>

  <div class="container-fluid mt-4 p-0">
    <% unless object.imageURL.empty? %>
      <div class="size-18 text-post">
        <%= object.content %>
      </div>
      <div class="center py-4">
        <%= image_tag(object.imageURL, class: "img-fill") %>
      </div>

      <% else %>
      <div class="size-18 text-post mb-2 ml-3">
        <%= object.content %>
      </div>
      <% end %>
      <% if current_user.id == object.user_path %>
        <%= link_to posts_path(object), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash hover-red"></i>
        <% end %>
      <% end %>
  </div>

  <div class="border-bottom border-top">
    <div class="container">
      <%= render 'likes/like_posts', object: object %>
    </div>
  </div>

  <div class="p1-5 py-2">
    <div class=""><%= render 'comments/comment', object: object %></div>
    <div class="col-10 mt-3">
      <%= render 'comments/form', object:object %>
    </div>
  </div>
</div>
<br>

app/views/posts/index.html.erb
<h1>Timeline - My posts and my friends posts</h1>
<div class="center font-raleway ">
  <%= link_to new_post_path, class:"btn btn-secondary" do %>
    New Post?
  <% end %>
</div>

<% @our_posts.each do |p| %>
  <% render 'posts/post_layout', object: p %>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-6 mx-auto">
  <h1 class="center bold">Say whats on your mind:</h1>
  <p>Create a new post</p>

  <%= form_for(@post) do |f| %>
    <%= render "devise/shared/error_messages", resource: @post %>
    <div class="form-group">
      <%= f.text_area :content, class:"form-control" %><br />
    </div>
    <div class="form-group">
      Image by URL:
      <p>To put an image in your pust enter the link to the image</p>
      <%= f.text_field :imageURL, class:"form-control" %>
      <br />
    </div>
    <div>
      <%= f.submit 'New Post', class:"btn btn-secondary col-md-3" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Post</h1>
<%= render 'posts/post_layout', object: @post %>