config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'comments/new'
  get 'comments/create'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/create'
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  put '/users/:id', to: 'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'
  
  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  get 'friendships/create'
  get 'users/index'
  get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_header.html.erb
<header class="fixed-top navbar-dark bg-dark shadow">

<div>
  <nav class="navbar navbar-expand-sm">
    <div class="navbar-header">
      <%= link_to posts_path, class:"text-light" do %>
        <%= image_tag("", id: "logo", class: "navbar-branch") %>
        <span class="text-white font-weight-bold font-courgette size-24">Odin</span>
      <% end %>
    </div>

<div class= "container mx-auto">
  <div class= "row mx-auto">
    <div class= "col-auto">
      <%= link_to posts_path, class: "text-light nav-link font-raleway" do %>
        <i class= "fas fa-home fa-2x"></i> Timeline
      <% end %>
    </div>
  </div>
</div>

<div class="col-auto">
  <%= link_to users_path, class: "text-light nav-link font-raleway" do%>
    <i class="fas fa-users fa-2x"></i>Find Friends
  <% end %>
</div>

<ul class="navbar-nav ml-auto">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= button_to saw_notice_path, :class => "text-white btn notice-btn-#{notification_seen}", data: {toggle: 'modal', target: '#noticeModal'}, method: :get, remote: true do %>
        <% if notification_seen %>
          <i class="fas fa-bell-slash"></i>
        <% else %>
          <i class="fas fa-bell"></i>
        <% end %>
      <% end %>
     </li>
     <li class="nav-item dropdown">
       <a id="navbarDropdown" class="nav-link dropdown-toggle font-raleway" href='#' role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Account <b class="caret"></b>
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to "My Profile", user_path(current_user), class: "dropdown-item font-raleway" %>
         <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item font-raleway", method: :delete %>
       </div>
     </li>
    <% end %>
  </ul>
</nav>
</div>
</header>

<% if user_signed_in? %>
  <%= render 'shared/notifications', object: current_user.notifications %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

<%= render 'layouts/header' %>
    <div class= 'container'>
      <br>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= yield %>
  </body>
</html>